name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 切出分支
        uses: actions/checkout@v3

      - name: 克隆 python_common 库并切出develop 分支
        run: |
          git clone https://github.com/WYN-GraduationProject/WYN-GraduationProject-common.git ./WYN-GraduationProject-common
          cd ./WYN-GraduationProject-common
          git checkout develop

      - name: 登录 Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 初始化 QEMU
        uses: docker/setup-qemu-action@v3

      - name: 初始化 Buildx
        uses: docker/setup-buildx-action@v3

      - name: docker 元数据
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: constantineqaq/face_server
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag
            type=ref,event=branch

      - name: 构建和推送
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
